##########################################################################################################
###########################################################################################################
###### [ General ]
# *********************************************************************************************************
###########################################################################################################
server:
  name: "example"
  port: "8080"


###########################################################################################################
###########################################################################################################
###### [ Management (https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html) ]
# *********************************************************************************************************
###########################################################################################################
management:
  server:
    port: "9080"
  endpoints:
    web:
      exposure:
        #include: [ "health" ]
        include: "*"
  health:
    livenessState:
      enabled: "true"
    readinessState:
      enabled: "true"
    diskSpace:
      enable: "true"
  endpoint:
    health:
      enabled: "true"
      show-details: "always"


###########################################################################################################
###########################################################################################################
###### [ Spring-boot ]
# *********************************************************************************************************
#  https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
###########################################################################################################
spring:
  application:
    name: "app-opera"
  main:
    allow-circular-references: "false"

###########################################################################################################
###########################################################################################################
###### [ My application settings ]
###########################################################################################################
application:
  servlet-filter:
    tracer:
      enabled: true
  spring-interceptor:
    request-logger:
      enabled: true;
  http-client:
    ozon:
      base-url: "https://tweakers.net"


###########################################################################################################
###########################################################################################################
###### [ OpenApi 3.1 & Swagger ] (https://springdoc.org/#properties)
###########################################################################################################
springdoc:
  api-docs:
    enabled: true
    version: "OPENAPI_3_1"
  show-actuator: true
  use-management-port: true
  auto-tag-classes: true


###########################################################################################################
###########################################################################################################
###### [ Logging ]
# *********************************************************************************************************
###########################################################################################################
logging:
  file:
    name: "/tmp/logs/app-opera.log"


###########################################################################################################
###########################################################################################################
###### [ Properties encryption ]
# *********************************************************************************************************
###########################################################################################################
jasypt:
  encryptor:
    password: "masterpassword"
    algorithm: "PBEWithMD5AndDES"
    key-obtention-iterations: "1000"
    pool-size: "1"
    string-output-type: "base64"

