services:

  app-template:
    image: "services/app-template:latest"
    restart: "always"
    ports:
      - "8080:8080" #web
      - "9080:9080" #actuator
    environment:
      - "PROPERTIES_CONFIG_ZIP=/mnt/config/config-local.zip"
      - "JASYPT_PWD=masterpassword"
    volumes:
      - "./../app-template/target/config-local.zip:/mnt/config/config-local.zip"
    networks:
      - "app-services-network"

  app-opera:
    image: "services/app-opera:latest"
    restart: "always"
    ports:
      - "8081:8081" #web
      - "9081:9081" #actuator
    environment:
      - "PROPERTIES_CONFIG_ZIP=/mnt/config/config-local.zip"
      - "JASYPT_PWD=masterpassword"
    volumes:
      - "./../app-opera/target/config-local.zip:/mnt/config/config-local.zip"
    networks:
      - "app-services-network"

  app-afwijk:
    image: "services/app-afwijk:latest"
    restart: "always"
    ports:
      - "8082:8082" #web
      - "9082:9082" #actuator
    environment:
      - "PROPERTIES_CONFIG_ZIP=/mnt/config/config-local.zip"
      - "JASYPT_PWD=masterpassword"
    volumes:
      - "./../app-afwijk/target/config-local.zip:/mnt/config/config-local.zip"
    networks:
      - "app-services-network"

networks:
  app-services-network:
    driver: "bridge"
    name: "app-services-network"
