##########################################################################################################
###########################################################################################################
###### [ General ]
# *********************************************************************************************************
###########################################################################################################
server:
  name: "example"
  port: "8080"


###########################################################################################################
###########################################################################################################
###### [ Management (https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html) ]
# *********************************************************************************************************
###########################################################################################################
management:
  server:
    port: "9080"
  endpoints:
    web:
      exposure:
        #include: [ "health" ]
        include: "*"
  health:
    livenessState:
      enabled: "true"
    readinessState:
      enabled: "true"
    diskSpace:
      enable: "true"
  endpoint:
    health:
      enabled: "true"
      show-details: "always"
  #------------------------------- BEGIN: tracing/openTelemetry/Jaeger -------------------------------#
  observations:
    enabled: true
    key-values:
      my-application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0 #100%
  otlp:
    enabled: true
    tracing:
      endpoint: "http://localhost:4318/v1/traces" #Jaeger
#------------------------------- END: tracing/openTelemetry/Jaeger -------------------------------#


###########################################################################################################
###########################################################################################################
###### [ Spring-boot ]
# *********************************************************************************************************
#  https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
###########################################################################################################
spring:
  application:
    name: "app-opera"
  main:
    allow-circular-references: "false"

###########################################################################################################
###########################################################################################################
###### [ My application settings ]
###########################################################################################################
application:
  servlet-filter:
    tracer:
      enabled: true
  spring-interceptor:
    request-logger:
      enabled: true;

# swagger-ui custom path
springdoc:
  show-actuator: true
  use-management-port: true

###########################################################################################################
###########################################################################################################
###### [ Logging ]
# *********************************************************************************************************
###########################################################################################################
logging:
  file:
    name: "/tmp/logs/app-opera.log"
